# Here is an example about how you can have the secrets required to run cloud-controller-manager.
# To generate an access/secret, see https://www.scaleway.com/en/docs/generate-an-api-token/
---
apiVersion: v1
kind: Secret
metadata:
  name: scaleway-secret
  namespace: kube-system
type: Opaque
stringData:
  SCW_ACCESS_KEY: "YOUR-ACCESS-KEY"
  SCW_SECRET_KEY: "YOUR-SECRET-KEY"
  SCW_DEFAULT_ORGANIZATION_ID: "YOUR-ORGANIZATION-ID"
  # Region is where your loadbalancer will be created, ex: fr-par, nl-ams
  SCW_DEFAULT_REGION: "fr-par"
