name: release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Enable experimental on dockerd
        run: |
          echo $'{\n    "experimental": true\n}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      - name: Get tag
        uses: olegtarasov/get-tag@v1
        id: tagName
      - name: Make release
        run: make release
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
          TAG: ${{ steps.tagName.outputs.tag }}
          IMAGE_TAG: ${{ steps.tagName.outputs.tag }}
